### ISSUE TITLE
[Linux] Build error with NuGet

### ISSUE THREAD

**Issue by christoffersch** [AtomicGameEngine/AtomicGameEngine#1141]
I'm getting some NuGet issues when trying to build Atomic. Might be worth looking into.

```
[100%] Building CXX object Source/AtomicNET/NETNative/CMakeFiles/AtomicNETNative.dir/__/__/__/__/Source/Generated/CSharp/Packages/AtomicPlayer/Native/CSPackageAtomicPlayer.cpp.o                               
[100%] Building CXX object Source/AtomicNET/NETNative/CMakeFiles/AtomicNETNative.dir/__/__/__/__/Source/Generated/CSharp/Packages/AtomicPlayer/Native/CSModulePlayer.cpp.o                                      
Linking CXX shared library libAtomicNETNative.so
[100%] Built target AtomicNETNative
/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Artifacts/Build/AtomicTool/AtomicTool net compile /media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Script/AtomicNET/AtomicNETProject.json -platform desktop -config Release -toolbootstrap
[Thu Nov 10 16:08:43 2016] INFO: Opened log file Atomic.log
[Thu Nov 10 16:08:43 2016] INFO: Created 3 worker threads
[Thu Nov 10 16:08:43 2016] INFO: Initialized engine
[Thu Nov 10 16:08:43 2016] INFO: bash : -c mono "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/Managed/nuget/nuget.exe" restore "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" && "xbuild" "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" /p:Platform="Any CPU" /p:Configuration=Release
[Thu Nov 10 16:08:47 2016] ERROR: 
MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib/mono/4.5'.
Restoring NuGet package System.Collections.Immutable.1.2.0.
Restoring NuGet package System.Reflection.Metadata.1.3.0.
WARNING: Unable to find version '1.3.0' of package 'System.Reflection.Metadata'.
  /home/christoffer/.local/share/NuGet/Cache: Package 'System.Reflection.Metadata.1.3.0' is not found on source '/home/christoffer/.local/share/NuGet/Cache'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  Error: TrustFailure (The authentication or decryption has failed.)
  The authentication or decryption has failed.
  The authentication or decryption has failed.
  Invalid certificate received from server. Error code: 0xffffffff800b0109

WARNING: Unable to find version '1.2.0' of package 'System.Collections.Immutable'.
  /home/christoffer/.local/share/NuGet/Cache: Package 'System.Collections.Immutable.1.2.0' is not found on source '/home/christoffer/.local/share/NuGet/Cache'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  Error: TrustFailure (The authentication or decryption has failed.)
  The authentication or decryption has failed.
  The authentication or decryption has failed.
  Invalid certificate received from server. Error code: 0xffffffff800b0109


Errors in packages.config projects
    Unable to find version '1.3.0' of package 'System.Reflection.Metadata'.
      /home/christoffer/.local/share/NuGet/Cache: Package 'System.Reflection.Metadata.1.3.0' is not found on source '/home/christoffer/.local/share/NuGet/Cache'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      Error: TrustFailure (The authentication or decryption has failed.)
      The authentication or decryption has failed.
      The authentication or decryption has failed.
      Invalid certificate received from server. Error code: 0xffffffff800b0109
    Unable to find version '1.2.0' of package 'System.Collections.Immutable'.
      /home/christoffer/.local/share/NuGet/Cache: Package 'System.Collections.Immutable.1.2.0' is not found on source '/home/christoffer/.local/share/NuGet/Cache'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      Error: TrustFailure (The authentication or decryption has failed.)
      The authentication or decryption has failed.
      The authentication or decryption has failed.
      Invalid certificate received from server. Error code: 0xffffffff800b0109

NuGet Config files used:
    /home/christoffer/.config/NuGet/NuGet.Config

Feeds used:
    /home/christoffer/.local/share/NuGet/Cache
    https://api.nuget.org/v3/index.json

Compilation Command: -c mono "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/Managed/nuget/nuget.exe" restore "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" && "xbuild" "/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" /p:Platform="Any CPU" /p:Configuration=Release

NETBuild Error for solution: /media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Script/AtomicNET/AtomicNETProject.json

/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
              ^
Error: Process exited with error.
    at api.fail (/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at null.<anonymous> (/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at emit (events.js:98:17)
    at ChildProcess.<anonymous> (/media/christoffer/36d87826-0cfb-43ea-a1fc-e6efcec24b63/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:809:12)

```

**Comment by christoffersch** [comment]
The problem was certificate issues and the solution was
`mozroots --import --sync`

Sorry for opening the issue!

**Comment by JoshEngebretson** [comment]
np, glad it is sorted and reference for others who may have the problem in the future
