### ISSUE TITLE
[Windows] Build failure during custom build step

### ISSUE THREAD

**Issue by Mustard867** [AtomicGameEngine/AtomicGameEngine#1598]
OS: Windows 10 Pro Insider Preview Build 16237
Source: Latest Master branch as of 7/9/2017

I am getting a build error during the custom build step of Atomic using the command line ".\Build_AtomicEditor.bat --vs2017 --with-android".

The custom build step prints this:

```
CustomBuild:
         Building Custom Rule C:/Users/cjb86/ROAGO/AtomicGameEngine/Source/AtomicTool/CMakeLists.txt
         CMake does not need to re-run because C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\Ato
         micTool\CMakeFiles\generate.stamp is up-to-date.
         genscripts: file zero size, regenerating script bindings: C:\Users\cjb86\ROAGO\AtomicGameEngine/Artifacts/Buil
         d/Source/Generated/Javascript/Packages/Atomic/JSPackageAtomic.cpp
         TSLINT: Linting files in {./Script/AtomicEditor/**/*.ts,./Script/AtomicWebViewEditor/**/*.ts}
         TSLINT: WARNING - Lint errors detected
         Script/AtomicEditor/editor/Preferences.ts[565, 1]: trailing whitespace
         Script/AtomicEditor/editor/Preferences.ts[494, 10]: missing semicolon
         Script/AtomicEditor/ui/AnimationToolbar.ts[99, 1]: trailing whitespace
         Script/AtomicEditor/ui/AnimationToolbar.ts[113, 1]: trailing whitespace
         Script/AtomicEditor/ui/AnimationToolbar.ts[103, 48]: missing whitespace
         Script/AtomicEditor/ui/AnimationToolbar.ts[103, 49]: missing whitespace
         Script/AtomicEditor/ui/frames/inspector/AttributeInfoEdit.ts[354, 1]: trailing whitespace
         Script/AtomicEditor/ui/frames/inspector/CreateComponentButton.ts[146, 6]: missing semicolon
         Script/AtomicEditor/ui/frames/menus/MainFrameMenu.ts[455, 7]: trailing whitespace
         Script/AtomicEditor/ui/frames/menus/MainFrameMenu.ts[459, 7]: trailing whitespace
         Script/AtomicEditor/ui/frames/ProjectFrame.ts[98, 1]: trailing whitespace
         Script/AtomicWebViewEditor/typings/monaco.d.ts[909, 32]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[909, 39]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[909, 51]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2674, 22]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2674, 33]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2717, 23]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2717, 30]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2717, 38]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2842, 20]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2842, 28]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2842, 35]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2842, 54]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2907, 31]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2907, 43]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2912, 32]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2912, 41]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2912, 49]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2970, 35]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2970, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2970, 52]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2979, 30]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2979, 38]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2979, 49]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[2979, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3022, 31]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3022, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3032, 28]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3032, 37]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3032, 50]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3047, 31]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3047, 40]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3047, 51]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3047, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 22]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 33]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 53]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 65]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 77]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 89]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 97]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 105]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 113]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 121]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 129]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 137]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 145]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3059, 153]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3208, 30]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3208, 41]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3250, 36]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3250, 45]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3250, 58]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3254, 39]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3254, 48]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3254, 59]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3254, 68]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3276, 43]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3276, 50]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3276, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3278, 38]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3278, 46]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3278, 57]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3278, 68]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3286, 39]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3286, 50]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3301, 39]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3301, 50]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[3301, 62]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5119, 49]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5119, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5119, 72]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5120, 37]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5120, 48]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5120, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5121, 44]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5121, 55]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5121, 67]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5122, 35]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5122, 46]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5122, 58]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5123, 40]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5123, 51]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5123, 63]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5124, 33]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5124, 44]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5124, 56]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5125, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5125, 53]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5125, 65]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5126, 34]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5126, 45]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5126, 57]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5127, 43]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5127, 54]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5127, 66]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5128, 39]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5128, 50]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5128, 62]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5129, 49]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5129, 60]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5129, 72]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5130, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5130, 53]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5130, 65]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5131, 31]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5131, 42]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5131, 54]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5132, 56]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5132, 67]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5132, 79]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5133, 52]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5133, 63]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5133, 75]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5134, 34]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5134, 45]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5134, 57]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5135, 30]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5135, 41]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5135, 53]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5136, 35]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5136, 46]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5136, 58]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5210, 34]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5210, 43]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5210, 53]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5210, 71]: ' should be "
         Script/AtomicWebViewEditor/typings/monaco.d.ts[5137, 10]: missing semicolon



         Lint: Typescript linting complete.


         [Sun Jul  9 15:26:03 2017] INFO: Opened log file Atomic.log
         [Sun Jul  9 15:26:03 2017] INFO: Created 3 worker threads
         [Sun Jul  9 15:26:03 2017] INFO: Initialized engine
         [Sun Jul  9 15:26:03 2017] INFO: Loading Package
         [Sun Jul  9 15:26:03 2017] INFO: Loading Package: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic
         /
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Container.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Math.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Core.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Scene.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Graphics.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Atomic2D.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Audio.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Physics.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Navigation.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Input.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         UI.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Resource.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Network.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         IO.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Engine.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Script.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Javascript.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Environment.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Web.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         IPC.json
         [Sun Jul  9 15:26:03 2017] INFO: Loading Module: C:/Users/cjb86/ROAGO/AtomicGameEngine/Script/Packages/Atomic/
         Metrics.json
         [Sun Jul  9 15:26:03 2017] INFO: Generating JS Bindings
         [Sun Jul  9 15:26:03 2017] INFO: Generating C# Bindings
         [Sun Jul  9 15:26:03 2017] INFO: WARNING: HttpRequest class didn't write a constructor, filling in generated n
         ative constructor
         jake aborted.
    71>CUSTOMBUILD : error : Process exited with error. [C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\
       Source\AtomicTool\AtomicToolCheckScripts.vcxproj]
             at api.fail (C:\Users\cjb86\ROAGO\AtomicGameEngine\Build\node_modules\jake\lib\api.js:336:18)
             at null.<anonymous> (C:\Users\cjb86\ROAGO\AtomicGameEngine\Build\node_modules\jake\lib\utils\index.js:124:
         9)
         (See full trace by running task with --trace)
    71>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicTool\AtomicToo
       lCheckScripts.vcxproj" (default targets) -- FAILED.
    40>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicTool\AtomicToo
       lCheckScripts.vcxproj.metaproj" (default targets) -- FAILED.
    37>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicApp\AtomicApp.
       vcxproj.metaproj" (default targets) -- FAILED.
    48>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicPlayerJS\Atomi
       cPlayerJS.vcxproj.metaproj" (default targets) -- FAILED.
     5>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicNET\NETNative\
       AtomicNETNative.vcxproj.metaproj" (default targets) -- FAILED.
     1>Done Building Project "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Atomic.sln" (LibCpuId;Atomi
       cNETNative target(s)) -- FAILED.

Build FAILED.
```

Looks like there are lint warnings/errors, but I'm not sure if that is what is causing the problems. And at the end of the build is this error:

```
     "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Atomic.sln" (LibCpuId;AtomicNETNative target) (1)
        ->
       "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicNET\NETNative\AtomicNETNative.vcxpro
       j.metaproj" (default target) (5) ->
       "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicApp\AtomicApp.vcxproj.metaproj" (def
       ault target) (37) ->
       "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicTool\AtomicToolCheckScripts.vcxproj.
       metaproj" (default target) (40) ->
       "C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Windows\Source\AtomicTool\AtomicToolCheckScripts.vcxproj"
        (default target) (71) ->
       (CustomBuild target) ->
         CUSTOMBUILD : error : Process exited with error. [C:\Users\cjb86\ROAGO\AtomicGameEngine\Artifacts\Build\Window
       s\Source\AtomicTool\AtomicToolCheckScripts.vcxproj]

    805 Warning(s)
    1 Error(s)
```

This is on a clean git pull with no modifications. It built fine a little while ago, so it must've been a recent commit. I installed Typescript 2.4.1 for Visual Studio but I haven't done that for node. Any idea what's going on here?

Thanks,
Christopher

**Comment by JoshEngebretson** [comment]
I built a clean pull of master on Windows 10 with VS 2017, both  the previous version and tested with update to v15.0.26430.15

@Mustard867 Did you try to build more than once?  You can also add the ```--noclean``` option in testing

Can anyone else replicate this?

**Comment by Mustard867** [comment]
Yeah, that's the same Visual Studio as I have. I tried building it again with --noclean with the same result. This could be an Insider Preview build issue. Microsoft has a habit of occasionally throwing in obscure issues with each release. If anyone else lives dangerously like I do and is also on the Windows Insider fast track, let me know if you can/can't build it.

**Comment by darrylryan** [comment]
I'm experiencing this same issue now... I've downgraded every component (code, VS, compiler) to earlier versions and still getting this weird problem.
I'm not on the insider fast track though, although I am on the slow track. 

The Jake error does look similar to this though reported on linux: https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1612

I didn't have any problems until I cleared and fully rebuilt everything from scratch though, so I wonder if maybe more people are affected but not seeing it due to having the bits already built/cached.

**Comment by JoshEngebretson** [comment]
@darrylryan The similarity is the CMake message of process exited with error, that Linux issue appears to be an issue with compiling... whereas this appears to be an issue with AtomicTool generating bindings.  You are on VS2017 and you have tried to build a clean master, right?  Do both the ```Build_AtomicEditor.bat``` and ```CMake_VS2017.bat``` result in this error?

**Comment by JoshEngebretson** [comment]
You can also try and invoke the bind command directly, from your local repo:

```C:\Dev\atomic\AtomicGameEngine>Artifacts\Build\AtomicTool\AtomicTool.exe bind C:\Dev\atomic\AtomicGameEngine\ Script\Packages\Atomic```

**Comment by darrylryan** [comment]
@JoshEngebretson I've tried building from the Build_AtomicEditor.bat, CMake_VS2017.bat, and from CMake gui, it still results in the same problem. I've done a clean checkout of the latest master, and also tried various points in time from the past, it still does it. I've tried completely reinstalling VS2017, and then again rolling back to the first 15.0 release of VS2017 without any updates (and checked the compiler version reported by CMake is indeed the older one) - it still happens. Its a very odd issue.

Running the bind command directly crashes at the same point (after the HttpRequest class warning) with a Windows 10 "AtomicTool.exe has stopped working" dialog box. Clicking the debug option in the dialog just gives the error:
Unhandled exception at 0x00007FFC57FFD2A6 (CoreMessaging.dll) in AtomicTool.exe: 0xC0000602:  A fail fast exception occurred. 

I've pulled in #1614 but the error still doesn't make a lot of sense to me:

1>[Fri Jul 28 14:17:16 2017] INFO: Loading Module: S:/Development/Atomic/AtomicGameEngine/Script/Packages/Atomic/Metrics.json
1>[Fri Jul 28 14:17:18 2017] INFO: Generating JS Bindings
1>[Fri Jul 28 14:17:19 2017] INFO: Generating C# Bindings
1>[Fri Jul 28 14:17:19 2017] INFO: WARNING: HttpRequest class didn't write a constructor, filling in generated native constructor
1>jake aborted.
1>CUSTOMBUILD : error : Process exited with error.
1>    at api.fail (S:\Development\Atomic\AtomicGameEngine\Build\node_modules\jake\lib\api.js:336:18)
1>    at null.<anonymous> (S:\Development\Atomic\AtomicGameEngine\Build\node_modules\jake\lib\utils\index.js:124:9)
1>    at emitTwo (events.js:88:13)
1>    at emit (events.js:173:7)
1>    at ChildProcess.<anonymous> (S:\Development\Atomic\AtomicGameEngine\Build\node_modules\jake\lib\utils\index.js:227:20)
1>    at emitTwo (events.js:88:13)
1>    at ChildProcess.emit (events.js:173:7)
1>    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
1>Done building project "GenerateScriptBindings.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 32 up-to-date, 0 skipped ==========

**Comment by JoshEngebretson** [comment]
From the VS solution, you should be able to debug into AtomicTool with the bind command and working directory set... and get a callstack.

**Comment by darrylryan** [comment]
![image](https://user-images.githubusercontent.com/3797848/28727200-e5bf061e-73bb-11e7-8513-8d08abd06240.png)

@JoshEngebretson It just seems to keep crashing in the KernelBase.dll
I guess I will try switching Windows to the fast track, maybe if it is a MS issue its fixed by now.

**Comment by JoshEngebretson** [comment]
I would strongly suggest using stable Windows for development.

**Comment by darrylryan** [comment]
I've been trying to get out of the insider builds for ages, but it has a life of its own. It won't let me go backwards or forwards right now.

**Comment by darrylryan** [comment]
....and now it builds.

2 days of fighting with git rollbacks, reinstalling visual studio, nuking my VS settings etc. and the solution turns out to be I needed a new Windows kernel.
Since I couldn't go backwards I had to go forwards to the preview release of Windows 10, and now it all just works again.

**Comment by JoshEngebretson** [comment]
Thanks for the report, filing that under good news 🍾
