### ISSUE TITLE
Failing to build on Linux

### ISSUE THREAD

**Issue by zaywolfe** [AtomicGameEngine/AtomicGameEngine#1612]
While running:
`./Build_AtomicEditor.sh --with-android --with-web --nonet --with-docs`

I end up with this error:
```
In file included from /home/zaya/apps/AtomicGameEngine/Artifacts/Build/Source/Generated/Javascript/Packages/Atomic/JSModuleCore.cpp:10:
/home/zaya/apps/AtomicGameEngine/Source/Atomic/../Atomic/Network/Network.h:30:10: fatal error: 'kNet/IMessageHandler.h' file not found
#include <kNet/IMessageHandler.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
Source/AtomicJS/CMakeFiles/AtomicJS.dir/build.make:758: recipe for target 'Source/AtomicJS/CMakeFiles/AtomicJS.dir/__/__/__/Source/Generated/Javascript/Packages/Atomic/JSModuleCore.cpp.o' failed
make[2]: *** [Source/AtomicJS/CMakeFiles/AtomicJS.dir/__/__/__/Source/Generated/Javascript/Packages/Atomic/JSModuleCore.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1470: recipe for target 'Source/AtomicJS/CMakeFiles/AtomicJS.dir/all' failed
make[1]: *** [Source/AtomicJS/CMakeFiles/AtomicJS.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
/home/zaya/apps/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (/home/zaya/apps/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at null.<anonymous> (/home/zaya/apps/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at ChildProcess.<anonymous> (/home/zaya/apps/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
I've been trying to find where I can get this header file but I'm at a complete loss... I'm running Elementary OS based on Ubuntu 16.04

**Comment by JimMarlowe** [comment]
That header file is (should be) included in the repo. Did you get the repo by zip file (which won't work) or by ` git clone --recursive https://github.com/AtomicGameEngine/AtomicGameEngine` (which should work as per https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-Atomic-from-Source#linux ).
The error looks like it may be happening in the `--with-web` phase. I can not build this phase at the moment to confirm this, my emscripten blew up and it's not reinstalling. I build the android phase regularly.
You should see if you can at least build Atomic without errors with `./Build_AtomicEditor.sh --nonet` If you can't do that, we'll need more information ( logs, etc ).

**Comment by hickscorp** [comment]
Same error here with a fresh cloned repo.

**Comment by JimMarlowe** [comment]
PR #1507 removed some include_directories in Source/AtomicJS/CMakeLists.txt this could be the source if these compilation problems for --with-web builds (only).
