### ISSUE TITLE
If path to source has directory with spaces, the .bat script / build script breaks

### ISSUE THREAD

**Issue by victorbstan** [AtomicGameEngine/AtomicGameEngine#1645]
I get the following error when trying to build 

```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine>Build_AtomicEditor.bat --vs2017


Building Atomic Editor, this process will take a few minutes

rm -rf E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine/Artifacts/AtomicEditor/
rm -rf E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine/Artifacts/AtomicNET/
rm -rf E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine/Artifacts/Build/Windows/
rm -rf E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine/Artifacts/Build/Source/Generated/
'E:\victo\Documents\Projects\Code\Atomic' is not recognized as an internal or external command,
operable program or batch file.
E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine\Build\node_modules\jake\lib\api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine\Build\node_modules\jake\lib\api.js:336:18)
    at null.<anonymous> (E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine\Build\node_modules\jake\lib\utils\
index.js:124:9)
    at emitTwo (events.js:88:13)
    at emit (events.js:173:7)
    at ChildProcess.<anonymous> (E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine\Build\node_modules\jake\li
b\utils\index.js:227:20)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)

E:\victo\Documents\Projects\Code\Atomic Game Engine\AtomicGameEngine>
```

**Comment by Alan-FGR** [comment]
Hi. Thank you for your report. As a temporary fix you could just remove the spaces from your path, this is a known problem:
https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1600

**Comment by victorbstan** [comment]
Thanks, I have and built successfully :)
