### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by ShalokShalom** [AtomicGameEngine/AtomicGameEngine#1649]
Did i forget something? 
```

[100%] Built target AtomicNETNative
/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Artifacts/Build/AtomicTool/AtomicTool net compile /home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Script/AtomicNET/AtomicNETProject.json -platform desktop -config Release -toolbootstrap
[Thu Sep  7 18:10:29 2017] INFO: Opened log file Atomic.log
[Thu Sep  7 18:10:29 2017] INFO: Created 3 worker threads
[Thu Sep  7 18:10:29 2017] INFO: Initialized engine
[Thu Sep  7 18:10:29 2017] INFO: bash : -c mono "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/Managed/nuget/nuget.exe" restore "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" && "xbuild" "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" /p:Platform="Any CPU" /p:Configuration=Release
[Thu Sep  7 18:10:36 2017] ERROR: 
MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib/mono/4.5'.
Restoring NuGet package System.Collections.Immutable.1.2.0.
Restoring NuGet package System.Reflection.Metadata.1.3.0.
WARNUNG: Unable to find version '1.3.0' of package 'System.Reflection.Metadata'.
  /home/matthias/.local/share/NuGet/Cache: Package 'System.Reflection.Metadata.1.3.0' is not found on source '/home/matthias/.local/share/NuGet/Cache'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request
  Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
  Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

WARNUNG: Unable to find version '1.2.0' of package 'System.Collections.Immutable'.
  /home/matthias/.local/share/NuGet/Cache: Package 'System.Collections.Immutable.1.2.0' is not found on source '/home/matthias/.local/share/NuGet/Cache'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request
  Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
  Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED


Errors in packages.config projects
    Unable to find version '1.3.0' of package 'System.Reflection.Metadata'.
      /home/matthias/.local/share/NuGet/Cache: Package 'System.Reflection.Metadata.1.3.0' is not found on source '/home/matthias/.local/share/NuGet/Cache'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
      Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
    Unable to find version '1.2.0' of package 'System.Collections.Immutable'.
      /home/matthias/.local/share/NuGet/Cache: Package 'System.Collections.Immutable.1.2.0' is not found on source '/home/matthias/.local/share/NuGet/Cache'.
      https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
      An error occurred while sending the request
      Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
      Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

NuGet Config files used:
    /home/matthias/.config/NuGet/NuGet.Config

Feeds used:
    /home/matthias/.local/share/NuGet/Cache
    https://api.nuget.org/v3/index.json

Compilation Command: -c mono "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/Managed/nuget/nuget.exe" restore "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" && "xbuild" "/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Artifacts/AtomicNET/Build/AtomicNET.sln" /p:Platform="Any CPU" /p:Configuration=Release

NETBuild Error for solution: /home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Script/AtomicNET/AtomicNETProject.json
/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at emitTwo (events.js:125:13)
    at Exec.emit (events.js:213:7)
    at ChildProcess.<anonymous> (/home/matthias/Projekte/KaOS/makepkg/atomic-game-engine-git/src/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
➜  atomic-game-engine-git 
```

**Comment by mattbenic** [comment]
Please give more details on what led to this including OS details, what project you're trying to build, etc.

**Comment by ShalokShalom** [comment]
KaOS and the current version of Atomic. 

This is the build script I use: 

https://gist.github.com/ShalokShalom/4d5827eddaf5e0820412f82465cebb0a
