### ISSUE TITLE
Building from source in windows - missing atomic.sln

### ISSUE THREAD

**Issue by Paruun** [AtomicGameEngine/AtomicGameEngine#1655]
As the title suggests I'm trying to build the engine from source. I'm getting an error telling me that the Atomic.sln is missing. It's not in the source and I can't see anywhere where it would be created. Any help appreciated.

C:\atomic>node ./Build/Scripts/Bootstrap.js buildeditor --vs2017 --opengl --with-android
Building Atomic Editor, this process will take a few minutes
OpenGL build selected.
rm -rf C:\atomic/Artifacts/AtomicEditor/
rm -rf C:\atomic/Artifacts/AtomicNET/
rm -rf C:\atomic/Artifacts/Build/Windows/
rm -rf C:\atomic/Artifacts/Build/Source/Generated/
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.3.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
The system cannot find the path specified.
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Atomic.sln
C:\atomic\Build\node_modules\jake\lib\api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (C:\atomic\Build\node_modules\jake\lib\api.js:336:18)
    at Exec.<anonymous> (C:\atomic\Build\node_modules\jake\lib\utils\index.js:124:9)
    at emitTwo (events.js:106:13)
    at Exec.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\atomic\Build\node_modules\jake\lib\utils\index.js:227:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)

**Comment by JoshEngebretson** [comment]
Use ```Atomic_BuildEditor.bat``` as per the instructions: 
 https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-Atomic-from-Source#windows

You can see the contents of the batch file here, which uses a local node + node_modules... you are using system node.

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Build_AtomicEditor.bat

**Comment by Paruun** [comment]
I used a different node as the batch file didn't work, petty much the same error. Here is the output of the batch file:

C:\atomic>build_atomiceditor.bat --vs2017 --opengl --with-android

Building Atomic Editor, this process will take a few minutes
OpenGL build selected.
rm -rf C:\atomic/Artifacts/AtomicEditor/
rm -rf C:\atomic/Artifacts/AtomicNET/
rm -rf C:\atomic/Artifacts/Build/Windows/
rm -rf C:\atomic/Artifacts/Build/Source/Generated/
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.3.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
The system cannot find the path specified.
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Atomic.sln
C:\atomic\Build\node_modules\jake\lib\api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (C:\atomic\Build\node_modules\jake\lib\api.js:336:18)
    at null.<anonymous> (C:\atomic\Build\node_modules\jake\lib\utils\index.js:124:9)
    at emitTwo (events.js:88:13)
    at emit (events.js:173:7)
    at ChildProcess.<anonymous> (C:\atomic\Build\node_modules\jake\lib\utils\index.js:227:20)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)

**Comment by JoshEngebretson** [comment]
I am guessing cmake isn't on your path:

```The system cannot find the path specified.```

**Comment by Paruun** [comment]
It's in my path, I can access it from the source directory:

C:\atomic>cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

C:\atomic>

**Comment by JoshEngebretson** [comment]
On VS2017, the build uses the CMake installed by VS2017 explicitly:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Build/Scripts/Windows/SetupVSEnvironment.bat#L12

This should probably be configurable and/or check for one on path to override it.  There should also be a better error message.

**Comment by Paruun** [comment]
Ok so reading through the JS files I came up with a 'quick fix':

1) Run the following to generate the .sln file
cmake /C /Build/Scripts/Windows/GenerateVSSolution.bat VS2017 ./ ./ -DATOMIC_DEV_BUILD=1 -DATOMIC_OPENGL=ON -DATOMIC_D3D11=OFF
2) Open the solution file in Visual Studio and build the solution.

That gave me a working EXE

**Comment by JoshEngebretson** [comment]
You could also change this line to just ```cmake```

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Build/Scripts/Windows/SetupVSEnvironment.bat#L12

This should use the cmake on the path, make the batch file work as expected, and also make the cmake bat file work with all the supported command line flags: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/How-to-set-up-a-Debug-Development-Build

**Comment by jellythedoge** [comment]
--vs2017 worked for me!
