### ISSUE TITLE
Error when building windows 10

### ISSUE THREAD

**Issue by jellythedoge** [AtomicGameEngine/AtomicGameEngine#1660]
`C:\Users\MEME\Documents\GitHub\AtomicGameEngine>Build_AtomicEditor.bat

Building Atomic Editor, this process will take a few minutes

rm -rf C:\Users\MEME\Documents\GitHub\AtomicGameEngine/Artifacts/AtomicEditor/
rm -rf C:\Users\MEME\Documents\GitHub\AtomicGameEngine/Artifacts/AtomicNET/
rm -rf C:\Users\MEME\Documents\GitHub\AtomicGameEngine/Artifacts/Build/Windows/
rm -rf C:\Users\MEME\Documents\GitHub\AtomicGameEngine/Artifacts/Build/Source/Generated/
'cmake' is not recognized as an internal or external command,
operable program or batch file.
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: Atomic.sln
C:\Users\MEME\Documents\GitHub\AtomicGameEngine\Build\node_modules\jake\lib\api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (C:\Users\MEME\Documents\GitHub\AtomicGameEngine\Build\node_modules\jake\lib\api.js:336:18)
    at null.<anonymous> (C:\Users\MEME\Documents\GitHub\AtomicGameEngine\Build\node_modules\jake\lib\utils\index.js:124:9)
    at emitTwo (events.js:88:13)
    at emit (events.js:173:7)
    at ChildProcess.<anonymous> (C:\Users\MEME\Documents\GitHub\AtomicGameEngine\Build\node_modules\jake\lib\utils\index.js:227:20)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)

C:\Users\MEME\Documents\GitHub\AtomicGameEngine>`

**Comment by jellythedoge** [comment]
Yea dont bother responding i will just install it on my arch Linux partition :/

**Comment by jellythedoge** [comment]
It failed on both but i found out i didnt declare Cmake or use --vs2017

even though i only have vs2017 it would fail without it!

**Comment by mattbenic** [comment]
Right, the default right now is to build with the 2015 toolchain if I remember correctly. There is currently some work going into rewriting the build process, so since you came right in the end I'm going to close this.
