### ISSUE TITLE
Error at the end of compilation and error on AEditor startup

### ISSUE THREAD

**Issue by Tom-III** [AtomicGameEngine/AtomicGameEngine#1674]
At the end of running ```Build_AtomicEditor.bat --vs2017``` I get this error
Also the FeaturesExamples project does not show up in Visual Studio don't know if this is related or not.
Also when running AtomicEditor I get this error ```"Error executing main.js"```

``` 
   20 Warning(s)
    0 Error(s)

Time Elapsed 00:04:23.63
fs.js:893
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'C:\Users\Tom\Documents\AtomicGam
eEngine\Artifacts\Build\Windows\Source\AtomicEditor\Release'
    at Error (native)
    at Object.fs.statSync (fs.js:893:18)
    at Object.copySync (C:\Users\Tom\Documents\AtomicGameEngine\Build\node_modul
es\fs-extra\lib\copy-sync\copy-sync.js:20:58)
    at copyAtomicEditor (C:\Users\Tom\Documents\AtomicGameEngine\Build\Scripts\B
uildWindows.js:27:8)
    at jake.exec.printStdout [as _callback] (C:\Users\Tom\Documents\AtomicGameEn
gine\Build\Scripts\BuildWindows.js:93:13)
    at utils.mixin._run (C:\Users\Tom\Documents\AtomicGameEngine\Build\node_modu
les\jake\lib\utils\index.js:239:18)
    at null._onTimeout (C:\Users\Tom\Documents\AtomicGameEngine\Build\node_modul
es\jake\lib\utils\index.js:231:45)
    at Timer.listOnTimeout (timers.js:93:15)
```

**Comment by NLDev** [comment]
Exactly same issue here. Is there any update on this?

**Comment by mattbenic** [comment]
I've just done a clean build from master using `Build_AtomicEditor.bat --vs2017` and had a successful build

You mention that the FeatureExamples project didn't show up, did you do a recursive clone of AtomicGameEngine? The examples (and CEF) exist in a submodule
