### ISSUE TITLE
Mac building error

### ISSUE THREAD

**Issue by angrycans** [AtomicGameEngine/AtomicGameEngine#1679]
mac 10.13.2
xcode 9.2
node v8.9.4

 ./Build_AtomicEditor.sh --with-ios --nonet

```
Libtool Artifacts/Build/Mac/Source/AtomicNET/NETScript/Release/libAtomicNETScript.a normal x86_64
    cd /Users/angrycans/Documents/github/AtomicGameEngine
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/angrycans/Documents/github/AtomicGameEngine/Artifacts/Build/Mac/Source/AtomicNET/NETScript/Release -filelist /Users/angrycans/Documents/github/AtomicGameEngine/Artifacts/Build/Mac/Source/AtomicNET/NETScript/Atomic.build/Release/AtomicNETScript.build/Objects-normal/x86_64/AtomicNETScript.LinkFileList -o /Users/angrycans/Documents/github/AtomicGameEngine/Artifacts/Build/Mac/Source/AtomicNET/NETScript/Release/libAtomicNETScript.a

** BUILD FAILED **


The following build commands failed:
	CompileC Artifacts/Build/Mac/Source/ToolCore/Atomic.build/Release/ToolCore.build/Objects-normal/x86_64/OpenAssetImporter.o Source/ToolCore/Import/OpenAssetImporter.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/angrycans/Documents/github/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (/Users/angrycans/Documents/github/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at null.<anonymous> (/Users/angrycans/Documents/github/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at emitTwo (events.js:88:13)
    at emit (events.js:173:7)
    at ChildProcess.<anonymous> (/Users/angrycans/Documents/github/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at emitTwo (events.js:88:13)
    at ChildProcess.emit (events.js:173:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)
```

**Comment by nick70** [comment]
https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1612

**Comment by LiljebergXYZ** [comment]
I'm currently experiencing the very same issue while building.
mac 10.13.2
xcode 9.0
node v8.5.0

**Comment by darrylryan** [comment]
There aren't any devs working on the Mac stuff at the moment so it might be a while until this is fixed.
It did *used* to build fine for Mac though so I would suggest rolling your git history back to around this time last year and see if it builds OK then. At least that proves the rest of your stack is OK and you have a usable binary.

**Comment by mattbenic** [comment]
If we can identify a last good commit for Mac, perhaps we can tag it for reference until we have a mac maintainer?

**Comment by franadoriv** [comment]
I have the same error on Mac 10.13.2. Fresh git clone, no spaces on path.

**Comment by visiomedia** [comment]
same error here on macos 10.13.3

**Comment by csningli** [comment]
Solved in my case (macosx 10.12.6, XCode 8.3.3, Qt 5.7). Try to build the editor with CMake directly. 

1.  cd into the root directory of the clone. 
2. open CMakeList.txt in editor and set the CMAKE_PREFIX_PATH to the directory containing Qt5Widgets. In my case, the following line has been added. 
  `set (CMAKE_PREFIX_PATH = /Applications/Qt5.7.0/5.7/clang_64/lib/cmake`
3. Save and quit CMakeList.txt. Run 
  `ccmake CMakeList.txt`
In ccmake window, select 'c' to configure. At the first time, it may not work and an error reported to  indicate sdk for MacOSX is not properly set. 
4. Select 'e' in ccmake window. Now you can see a list of configuration entries. Find 'CMAKE_BUILD_TYPE' and set it to 'Release'; Find 'CMAKE_OSX_DEPLOYMENT_TARGET' and set it to your version of macos (in my case, it's 10.12); Find 'CMAKE_OSX_SYSROOT' and set it to the position of MacOSX sdk in your XCode (in my case, its /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk).
5. Select 'c' again and this time the configuration should be done successfully. You can see there is one more option to generate. 
6. Select 'g' to generate. When the generation is done, you can run 'make' to build the AtomieEditor.app. The newly built .app file is inside Source/AtomieEditor/  .
7. Run the following line under the root directory to fix the Chromium Embedded Framework.  
`cp -r Submodules/CEF/MacOSX/Release/Chromium\ Embedded\ Framework.framework ./Source/AtomicEditor/AtomicEditor.app/Contents/Frameworks/`
8. Now you can start the editor by going into Source/AtomicEditor and run 
`./AtomicEditor.app/Content/MacOS/AtomicEditor`. The Editor window will show up if everything has been done correctly. 

Comments:
1. If you use 10.7 sdks, as indicated by default. You may encounter with the errors complaining something like "comparison between pointer and integer". Find the comparison and replace '> 0' with ' != (void *) NULL'.
2. If you encounter with errors in building the examples, try to comment the last part in CMakeList.txt. 
'
if (ATOMIC_DESKTOP AND ATOMIC_DEV_BUILD)
    if (NOT DEFINED ATOMIC_CPLUSPLUS_EXAMPLES)
        set(ATOMIC_CPLUSPLUS_EXAMPLES 1)
    endif ()
    if (ATOMIC_CPLUSPLUS_EXAMPLES)
        initialize_submodule(${ATOMIC_SOURCE_DIR}/Submodules/AtomicExamples ATOMIC_CPLUSPLUS_EXAMPLES)
        if (ATOMIC_CPLUSPLUS_EXAMPLES)
            add_subdirectory(Submodules/AtomicExamples/FeatureExamples/CPlusPlus)
        endif ()
    endif ()
endif ()
'

**Comment by mattbenic** [comment]
@csningli would you be able to do a PR to get Atomic building on latest OSX tools?

**Comment by csningli** [comment]
@mattbenic have you tried on maxos 10.13 with all '10.12' in my suggestion replaced with '10.13' ? does it show any errors?

**Comment by csningli** [comment]
Well, there are still some errors when building with Build_AtomicEditor.sh.
I will try to fix it and do a PR if everything get to work :)


--

Li @ Shenzhen ChoirTech Ltd.

**Comment by mattbenic** [comment]
Thanks, that would be greatly appreciated :)

**Comment by Tekh-ops** [comment]
Error copying directory from "/Users/mac/temp/AtomicGameEngine/Submodules/CEF/MacOSX/Release/CEF.framework" to "/Users/mac/temp/AtomicGameEngine/Source/AtomicEditor/AtomicEditor.app/Contents/Frameworks/CEF.framework".
make[2]: *** [Source/AtomicEditor/AtomicEditor.app/Contents/MacOS/AtomicEditor] Error 1
make[2]: *** Deleting file `Source/AtomicEditor/AtomicEditor.app/Contents/MacOS/AtomicEditor'
make[1]: *** [Source/AtomicEditor/CMakeFiles/AtomicEditor.dir/all] Error 2
make: *** [all] Error 2

I followed all the instructions but can find the Atomic Editor Executable

**Comment by Tekh-ops** [comment]
It deletes the mac executable
