### ISSUE TITLE
Error build in Linux 

### ISSUE THREAD

**Issue by ghost** [AtomicGameEngine/AtomicGameEngine#1710]
```
[ 75%] Built target Assimp
make[1]: *** [CMakeFiles/Makefile2:2210: Source/AtomicNET/NETNative/CMakeFiles/AtomicNETNative.dir/rule] Ошибка 2
make: *** [Makefile:605: AtomicNETNative] Ошибка 2
/home/tannicarcher/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (/home/tannicarcher/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/home/tannicarcher/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at Exec.emit (node:events:513:28)
    at ChildProcess.<anonymous> (/home/tannicarcher/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

Node.js v18.13.0

```

**Comment by GorEldeen** [comment]
Brother I don't think the devs are updating this engine anymore

**Comment by ghost** [comment]
> Brother I don't think the devs are updating this engine anymore

![image](https://github.com/AtomicGameEngine/AtomicGameEngine/assets/113786861/25a15259-3a39-4413-a999-881aa36154dc)

so i build it 

Using Windows 10 Enterprise 64 bit 
2GB RAM
AMD-C60 CPU
Amd radeon 6290 hd graphics

**Comment by GorEldeen** [comment]
Oh congrats! you got it working :)
